//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_EFTelefonRehberi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilgiler
    {
        public string PersonelId { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public Nullable<int> PersonelTel { get; set; }
    }
}
